### ISSUE TITLE
Add remove() api in RedBlackTree implementation

### ISSUE THREAD

**Issue by bhaskar253** [williamfiset/Algorithms#118] opened 2020-01-19 02:41 UTC
RedBlackTree implementation is missing the 

> remove(T elem)

**Comment by williamfiset** [comment] 2020-01-21 05:09
Agreed, this would be nice. Feel free to send a PR

**Comment by bhaskar253** [comment] 2020-01-23 13:59
Hey @williamfiset, I tried implementing but I am not able to handle root node deletion.

**Comment by abstratt** [comment] 2020-02-02 13:22
Same as #80?

**Comment by williamfiset** [comment] 2020-02-02 17:42
Duplicate of #80, thanks Rafael

**Closed by williamfiset** 2020-02-02 17:42 UTC
